const WA="+919939995360";
const PAYMENT_LINK="PASTE_YOUR_PAYMENT_LINK_HERE";
const packages=[
{id:"buddhist",cat:"pilgrimage",title:"Buddhist Circuit Pilgrimage",duration:"5 Days / 4 Nights",route:"Bodh Gaya → Rajgir → Nalanda → Varanasi → Kushinagar",price:12500,img:"https://upload.wikimedia.org/wikipedia/commons/b/b3/Mahabodhi_Temple_-_Bodh_Gaya.jpg"},
{id:"golden",cat:"heritage",title:"Golden Triangle Classic Tour",duration:"6 Days / 5 Nights",route:"Delhi → Agra → Jaipur → Delhi",price:16000,img:"https://images.unsplash.com/photo-1564507592333-c60657eea523?q=80&w=900&auto=format&fit=crop"},
{id:"sikkim",cat:"hills",title:"Gangtok & Sikkim Hill Odyssey",duration:"6 Days / 5 Nights",route:"NJP / Bagdogra → Gangtok → Tsomgo Lake → Darjeeling",price:18500,img:"https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=900&auto=format&fit=crop"},
{id:"chardham",cat:"pilgrimage",title:"Sacred Char Dham Yatra",duration:"10 Days / 9 Nights",route:"Haridwar → Yamunotri → Gangotri → Kedarnath → Badrinath",price:28000,img:"https://images.unsplash.com/photo-1506015391300-4802dc74de2e?q=80&w=900&auto=format&fit=crop"},
{id:"kerala",cat:"south",title:"Kerala Backwaters & Hills Tour",duration:"6 Days / 5 Nights",route:"Cochin → Munnar → Thekkady → Alleppey Houseboat",price:17500,img:"https://images.unsplash.com/photo-1593693397690-362cb9666fc2?q=80&w=900&auto=format&fit=crop"},
{id:"rajasthan",cat:"heritage",title:"Royal Rajasthan Heritage Explorer",duration:"7 Days / 6 Nights",route:"Jaipur → Jodhpur → Udaipur → Ajmer / Pushkar",price:19500,img:"https://images.unsplash.com/photo-1599661046289-e31897846e41?q=80&w=900&auto=format&fit=crop"}
];
let currentCat="all"; document.getElementById("year").textContent=new Date().getFullYear();
function render(list=packages){document.getElementById("cards").innerHTML=list.map(p=>`<article class="card"><img src="${p.img}" alt="${p.title}"><div class="card-body"><small>${p.cat.toUpperCase()}</small><h3>${p.title}</h3><p>${p.duration}</p><p>📍 ${p.route}</p><div class="price">₹${p.price.toLocaleString("en-IN")} <small>/ person*</small></div><div class="card-actions"><button class="btn" onclick="whatsapp('Hello, I am interested in ${p.title} (${p.duration}). Please send final quotation.')">💬 Enquire</button><button class="btn primary" onclick="pay()">💳 Pay</button></div></div></article>`).join("")}
function setCat(cat){currentCat=cat;filterCards()}
function filterCards(){const q=document.getElementById("search").value.toLowerCase();render(packages.filter(p=>(currentCat==="all"||p.cat===currentCat)&&`${p.title} ${p.route} ${p.cat}`.toLowerCase().includes(q)))}
function whatsapp(text){window.open("https://wa.me/"+WA+"?text="+encodeURIComponent(text),"_blank","noopener")}
function submitEnquiry(e){e.preventDefault();let t=`Hello Sariputra Tour & Holidays,\n\nTravel quotation request\nName: ${name.value}\nMobile: ${phone.value}\nDate: ${date.value||"Not decided"}\nVehicle: ${vehicle.value}\nDestination: ${destination.value}\nPassengers: ${people.value||"Not specified"}\nDays: ${days.value||"Not specified"}\nRequirements: ${message.value||"None"}`;whatsapp(t)}
function pay(){if(PAYMENT_LINK==="PASTE_YOUR_PAYMENT_LINK_HERE"){alert("Please set your real payment link in frontend/app.js → PAYMENT_LINK.");return}window.open(PAYMENT_LINK,"_blank","noopener")}
function openAI(){document.getElementById("ai").classList.add("open"); if(!document.getElementById("chat").innerHTML)bot("Hello! I can help you choose a package, vehicle or prepare a booking enquiry.")}
function closeAI(){document.getElementById("ai").classList.remove("open")}
function bot(t){document.getElementById("chat").innerHTML+=`<div class="msg">🤖 ${t}</div>`;window.lastAnswer=t}
function askAI(){let q=document.getElementById("aiInput").value.trim();if(!q)return;document.getElementById("chat").innerHTML+=`<div class="msg me">${q}</div>`;document.getElementById("aiInput").value="";let a="I can help with Buddhist Circuit, Golden Triangle, Sikkim, Char Dham, Kerala and Rajasthan packages. Tell me destination, travellers and trip days.";if(/vehicle|bus|seat/i.test(q))a="Available vehicles: 7 seater, 17 seater Urbania, 17 seater Tempo Traveller, 35 seater, 45 seater and 49 seater buses.";else if(/price|cost|package/i.test(q))a="Packages currently start from ₹12,500/person in the supplied package data. Final pricing should be confirmed for your dates and group.";else if(/whatsapp|book/i.test(q))a="I can prepare the enquiry for WhatsApp. Use the booking form or WhatsApp button.";bot(a)}
function speakLast(){if(window.lastAnswer&&"speechSynthesis"in window)speechSynthesis.speak(new SpeechSynthesisUtterance(window.lastAnswer))}
function speakInput(){if(!("webkitSpeechRecognition"in window||"SpeechRecognition"in window)){alert("Speech recognition is not supported in this browser.");return}let R=window.SpeechRecognition||window.webkitSpeechRecognition,r=new R();r.lang="en-IN";r.onresult=e=>{document.getElementById("aiInput").value=e.results[0][0].transcript;askAI()};r.start()}
render();